### ISSUE TITLE
Clean install Error

### ISSUE THREAD

**Issue by andrenventer** [isisaddons/isis-app-neoapp#2] opened 2016-04-11 20:32 UTC
After running:
$ mvn clean install

I see the following

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Neo App ............................................ SUCCESS [  0.250 s]
[INFO] Neo App DOM ........................................ SUCCESS [  8.911 s]
[INFO] Neo App Fixtures ................................... FAILURE [ 20.828 s]
[INFO] Neo App Integration Tests .......................... SKIPPED
[INFO] Neo App Server (port 7474) ......................... SKIPPED
[INFO] Neo App Webapp ..................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 30.265 s
[INFO] Finished at: 2016-04-11T22:28:27+02:00
[INFO] Final Memory: 25M/388M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project neoapp-fixture: Could not resolve dependencies for project org.isisaddons.app:neoapp-fixture:jar:1.11.0-SNAPSHOT: Could not find artifact org.isisaddons.app:neoapp-dom:jar:1.10.0-SNAPSHOT in apache.snapshots (https://repository.apache.org/content/repositories/snapshots/) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :neoapp-fixture

**Comment by danhaywood** [comment] 2016-04-12 07:42
Since this is only an example and we don't use neo4j ourseves, I must admit
we don't give this repo very much love.  Looks like the issue is that the
app has dependencies on -SNAPSHOT.   Do you want to try it out with the
latest version (v1.12.1).  If it works, please raise a PR for that.

Thx
Dan

**Comment by danhaywood** [comment] 2016-06-17 11:18
At least in 1.13.0-SNAPSHOT this is now building fine, so I'm going to close this ticket.

**Closed by danhaywood** 2016-06-17 11:18 UTC
